[package]
name = "csr"
version = "0.1.0"
edition = "2021"

[lib]

[workspace]

members = ["csr_examples", "csr_trait", "csr_derive"]

[dependencies]
const_format = "0.2.32"
# csr_derive = { path = "csr_derive" }
# csr_trait = { path = "csr_trait" }
# csr_examples = { path = "csr_examples" }
